<!DOCTYPE html>
<html>
<head>
    <title>Incident Reports - {{ now()->format('F j, Y') }}</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            font-size: 10px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 { 
            margin: 0; 
            font-size: 20px;
            color: #333;
        }
        .header p { 
            margin: 5px 0 0;
            color: #666;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 15px;
            font-size: 9px;
        }
        th, td { 
            border: 1px solid #ddd; 
            padding: 5px; 
            text-align: left; 
            vertical-align: top;
            word-wrap: break-word;
            white-space: normal;
        }
        th { 
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer { 
            margin-top: 20px; 
            text-align: right; 
            font-size: 10px;
            color: #777;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }
        small {
            font-size: 8px;
            color: #666;
        }
        .status-pending { color: #f39c12; font-weight: bold; }
        .status-in_progress { color: #3498db; font-weight: bold; }
        .status-resolved { color: #00a65a; font-weight: bold; }
        .status-rejected { color: #dd4b39; font-weight: bold; }
        @page {
            margin: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Barangay Kalawag II</h1>
        <p>Incident Reports</p>
        <p>Generated on {{ now()->format('F j, Y g:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Reporter</th>
                <th>Contact Number</th>
                <th>Incident Type</th>
                <th>Description</th>
                <th>Location</th>
                <th>Status</th>
                <th>Date Reported</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reports as $report)
                @php($uiStatusKey = in_array($report->status, ['rejected', 'invalid'], true) ? 'invalid' : (in_array($report->status, ['pending','in_progress'], true) ? $report->status : 'closed'))
                @php($uiStatusLabel = $uiStatusKey === 'pending' ? 'Pending' : ($uiStatusKey === 'in_progress' ? 'In Progress' : ($uiStatusKey === 'invalid' ? 'Invalid' : 'Closed/Completed')))
                <tr>
                    <td>#{{ $report->id }}</td>
                    <td>
                        @php($reporterName = trim((string) ($report->reporter_name ?? (optional($report->user)->full_name ?: optional($report->user)->name))))
                        {{ $reporterName !== '' ? $reporterName : ($report->is_anonymous ? 'Anonymous' : 'Unknown') }}
                        @if(!empty(optional($report->user)->email))
                            <br><small>{{ optional($report->user)->email }}</small>
                        @endif
                    </td>
                    <td>{{ $report->contact_number ?? optional($report->user)->contact_number ?? '' }}</td>
                    <td>{{ $report->incident_type === 'other' ? ($report->incident_type_other ?? 'Other') : (\App\Models\IncidentReport::TYPES[$report->incident_type] ?? ucfirst(str_replace('_',' ', $report->incident_type))) }}</td>
                    <td>{{ Str::limit($report->description, 100) }}</td>
                    <td>
                        {{ $report->location ?? '' }}
                        @if(!empty(optional($report->purok)->name))
                            <br><small>{{ $report->purok->name }}</small>
                        @endif
                    </td>
                    <td class="status-{{ $uiStatusKey }}">
                        {{ $uiStatusLabel }}
                    </td>
                    <td>{{ optional($report->created_at)->format('M d, Y h:i A') ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Incident Reports: {{ count($reports) }}</p>
        <p>Report generated by {{ auth()->user()->name }}</p>
    </div>
</body>
</html>
