<!DOCTYPE html>
<html>
<head>
    <title>Incident Reports - {{ now()->format('F j, Y') }}</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            font-size: 10px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 { 
            margin: 0; 
            font-size: 20px;
            color: #333;
        }
        .header p { 
            margin: 5px 0 0;
            color: #666;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 15px;
            font-size: 9px;
        }
        th, td { 
            border: 1px solid #ddd; 
            padding: 5px; 
            text-align: left; 
        }
        th { 
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer { 
            margin-top: 20px; 
            text-align: right; 
            font-size: 10px;
            color: #777;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }
        small {
            font-size: 8px;
            color: #666;
        }
        .status-pending { color: #f39c12; font-weight: bold; }
        .status-in_progress { color: #3498db; font-weight: bold; }
        .status-resolved { color: #00a65a; font-weight: bold; }
        .status-rejected { color: #dd4b39; font-weight: bold; }
        @page {
            margin: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Barangay Kalawag II</h1>
        <p>Incident Reports</p>
        <p>Generated on {{ now()->format('F j, Y g:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Reporter</th>
                <th>Incident Type</th>
                <th>Description</th>
                <th>Location</th>
                <th>Status</th>
                <th>Date Reported</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reports as $report)
                <tr>
                    <td>#{{ $report->id }}</td>
                    <td>
                        {{ $report->user->first_name ?? 'Unknown' }} {{ $report->user->last_name ?? '' }}<br>
                        <small>{{ $report->user->email ?? 'N/A' }}</small>
                    </td>
                    <td>{{ $report->incident_type }}</td>
                    <td>{{ Str::limit($report->description, 100) }}</td>
                    <td>
                        {{ $report->purok->name ?? 'N/A' }}<br>
                        <small>{{ $report->location ?? 'No specific location' }}</small>
                    </td>
                    <td class="status-{{ $report->status }}">
                        {{ format_label($report->status) }}
                    </td>
                    <td>{{ $report->created_at->format('M d, Y h:i A') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Incident Reports: {{ count($reports) }}</p>
        <p>Report generated by {{ auth()->user()->name }}</p>
    </div>
</body>
</html>
