<!DOCTYPE html>
<html>
<head>
    <title>Purok Clearance Requests Report - {{ now()->format('F j, Y') }}</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            font-size: 10px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 { 
            margin: 0; 
            font-size: 20px;
            color: #333;
        }
        .header p { 
            margin: 5px 0 0;
            color: #666;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 15px;
            font-size: 9px;
        }
        th, td { 
            border: 1px solid #ddd; 
            padding: 5px; 
            text-align: left; 
        }
        th { 
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer { 
            margin-top: 20px; 
            text-align: right; 
            font-size: 10px;
            color: #777;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }
        small {
            font-size: 8px;
            color: #666;
        }
        .status-pending { color: #f39c12; font-weight: bold; }
        .status-approved { color: #00a65a; font-weight: bold; }
        .status-completed { color: #00a65a; font-weight: bold; }
        .status-rejected { color: #dd4b39; font-weight: bold; }
        @page {
            margin: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Barangay Kalawag II</h1>
        <p>Purok Clearance Requests Report</p>
        <p>Generated on {{ now()->format('F j, Y g:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Resident</th>
                <th>Purpose</th>
                <th>Purok</th>
                <th>Status</th>
                <th>Date Requested</th>
            </tr>
        </thead>
        <tbody>
            @foreach($requests as $request)
                <tr>
                    <td>#{{ $request->id }}</td>
                    <td>
                        @php($residentName = $request->requester_name ?? (optional($request->user)->full_name ?: optional($request->user)->name))
                        {{ $residentName ?: 'N/A' }}<br>
                        <small>{{ $request->email ?? optional($request->user)->email ?? 'N/A' }}</small>
                    </td>
                    <td>{{ $request->purpose ?? 'N/A' }}</td>
                    <td>{{ $request->purok->name ?? 'N/A' }}</td>
                    <td class="status-{{ $request->status }}">
                        {{ format_label($request->status) }}
                    </td>
                    <td>{{ $request->created_at->format('M d, Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Requests: {{ count($requests) }}</p>
        <p>Report generated by {{ auth()->user()->name }}</p>
    </div>
</body>
</html>
