<!DOCTYPE html>
<html>
<head>
    <title>Purok Leaders Report - {{ now()->format('F j, Y') }}</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            font-size: 11px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 { 
            margin: 0; 
            font-size: 20px;
            color: #333;
        }
        .header p { 
            margin: 5px 0 0;
            color: #666;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 15px;
            font-size: 10px;
        }
        th, td { 
            border: 1px solid #ddd; 
            padding: 6px; 
            text-align: left; 
        }
        th { 
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer { 
            margin-top: 20px; 
            text-align: right; 
            font-size: 10px;
            color: #777;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }
        small {
            font-size: 9px;
            color: #666;
        }
        @page {
            margin: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Barangay Kalawag II</h1>
        <p>Purok Leaders Report</p>
        <p>Generated on {{ now()->format('F j, Y g:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Purok</th>
                <th>Contact Number</th>
                <th>DOB</th>
                <th>Sex</th>
                <th>Date Assigned</th>
            </tr>
        </thead>
        <tbody>
            @foreach($leaders as $index => $leader)
                @php($rbi = $leader->latestResidentRecord)
                <tr>
                    <td>{{ $rbi?->first_name ?? $leader->first_name }} {{ $rbi?->middle_name ?? $leader->middle_name }} {{ $rbi?->last_name ?? $leader->last_name }}</td>
                    <td>{{ $leader->purok->name ?? 'N/A' }}</td>
                    <td>{{ $rbi?->contact_number ?? $leader->contact_number ?? $leader->phone_number ?? 'N/A' }}</td>
                    <td>{{ $rbi?->birth_date?->format('Y-m-d') ?? ($leader->birth_date ? $leader->birth_date->format('Y-m-d') : ($leader->date_of_birth ?? 'N/A')) }}</td>
                    <td>{{ $rbi?->sex ?? $leader->sex ?? $leader->gender ?? 'N/A' }}</td>
                    <td>{{ $leader->created_at->format('M d, Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Purok Leaders: {{ count($leaders) }}</p>
        <p>Report generated by {{ auth()->user()->name }}</p>
    </div>
</body>
</html>
