<!DOCTYPE html>
<html>
<head>
    <title>Residents Report - {{ now()->format('F j, Y') }}</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 { 
            margin: 0; 
            font-size: 20px;
            color: #333;
        }
        .header p { 
            margin: 5px 0 0;
            color: #666;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 15px;
            font-size: 11px;
        }
        th, td { 
            border: 1px solid #ddd; 
            padding: 6px; 
            text-align: left; 
        }
        th { 
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer { 
            margin-top: 20px; 
            text-align: right; 
            font-size: 10px;
            color: #777;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }
        @page {
            margin: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Barangay Kalawag II</h1>
        <p>Residents Report</p>
        <p>Generated on {{ now()->format('F j, Y g:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>No.</th>
                <th>Full Name</th>
                <th>Gender</th>
                <th>Civil Status</th>
                <th>Date of Birth</th>
                <th>Age</th>
                <th>Address</th>
                <th>Contact Info</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($residents as $index => $resident)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $resident->first_name }} {{ $resident->middle_name }} {{ $resident->last_name }}</td>
                    <td>{{ ucfirst($resident->gender) }}</td>
                    <td>{{ format_label($resident->civil_status) }}</td>
                    <td>{{ $resident->birth_date ? $resident->birth_date->format('M d, Y') : 'N/A' }}</td>
                    <td>{{ $resident->birth_date ? $resident->birth_date->age . ' yrs' : 'N/A' }}</td>
                    <td>
                        {{ $resident->purok->name ?? 'N/A' }}<br>
                        <small>{{ $resident->address }}</small>
                    </td>
                    <td>
                        {{ $resident->email }}<br>
                        <small>{{ $resident->contact_number }}</small>
                    </td>
                    <td>{{ $resident->is_approved ? 'Approved' : 'Pending' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Residents: {{ count($residents) }}</p>
        <p>Report generated by {{ auth()->user()->name }}</p>
    </div>
</body>
</html>
